a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0


In [1]:
import numpy as np

# a. Create random vector of size 15 with integers in range 1-20
arr = np.random.randint(1, 21, size=15)

# 1. Reshape the array to 3 by 5
arr = arr.reshape(3, 5)

# 2. Print array shape
print("Array shape:", arr.shape)

# 3. Replace the max in each row with 0
for i in range(arr.shape[0]):
    row_max = arr[i].max()
    arr[i][arr[i] == row_max] = 0

print("Modified array:\n", arr)

Array shape: (3, 5)
Modified array:
 [[10  3  0  2  5]
 [14 15 14  0 14]
 [ 0  0 16  7  5]]


b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [2]:
# Create a 4x3 array with 4-byte integers (int32)
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]], dtype=np.int32)

# Print shape, type, and data type
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)

Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [3]:
import numpy as np

# Given square array
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


d. Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]


In [4]:
import numpy as np

# Given array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Compute the sum of diagonal elements
# Only the elements where row index == column index are on the main diagonal
diagonal_sum = np.trace(arr)

print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


e. Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]


In [5]:
import numpy as np

# Original 3x2 array
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

# Reshape to 2x3
reshaped_arr = arr.reshape(2, 3)

print("Original array (3x2):\n", arr)
print("\nReshaped array (2x3):\n", reshaped_arr)

Original array (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
